# Generated by Django 2.1.3 on 2019-07-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTS_INFO',
            fields=[
                ('i_d', models.AutoField(primary_key=True, serialize=False)),
                ('bts_type', models.CharField(blank=True, max_length=225, null=True)),
                ('bts_use', models.CharField(blank=True, max_length=225, null=True)),
                ('bts_name', models.CharField(blank=True, max_length=225, null=True)),
                ('rack', models.CharField(blank=True, max_length=225, null=True)),
                ('switch_port', models.CharField(blank=True, max_length=225, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BTS_MODULES',
            fields=[
                ('i_d', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(blank=True, max_length=225, null=True)),
                ('module_brand', models.CharField(blank=True, max_length=225, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=225, null=True)),
                ('product_number', models.CharField(blank=True, max_length=225, null=True)),
                ('asset_number', models.CharField(blank=True, max_length=225, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assign', models.CharField(blank=True, choices=[('0', '0'), ('1', '1')], default='0', max_length=1, null=True)),
                ('bts_info_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_mod', to='rpcTrack.BTS_INFO')),
            ],
        ),
        migrations.CreateModel(
            name='BTS_PC',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=225)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('domain', models.CharField(blank=True, max_length=225, null=True)),
                ('ue_type', models.CharField(max_length=225)),
                ('fetch', models.IntegerField(default=0)),
                ('rack', models.CharField(blank=True, max_length=225, null=True)),
                ('switch_port', models.CharField(blank=True, max_length=225, null=True)),
                ('check', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=225, null=True)),
                ('product_number', models.CharField(blank=True, max_length=225, null=True)),
                ('asset_number', models.CharField(blank=True, max_length=225, null=True)),
                ('bts_info_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bts_info_id_for', to='rpcTrack.BTS_INFO')),
                ('bts_mod1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bts_mod_1', to='rpcTrack.BTS_MODULES')),
                ('bts_mod2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bts_mod_2', to='rpcTrack.BTS_MODULES')),
                ('bts_mod3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bts_mod_3', to='rpcTrack.BTS_MODULES')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('name', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='TM500_INFO',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('rack', models.CharField(blank=True, max_length=225, null=True)),
                ('switch_port', models.CharField(blank=True, max_length=225, null=True)),
                ('notes', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=225, null=True)),
                ('product_number', models.CharField(blank=True, max_length=225, null=True)),
                ('asset_number', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TM500_PC',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=225)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('domain', models.CharField(blank=True, max_length=225, null=True)),
                ('rack', models.CharField(blank=True, max_length=225, null=True)),
                ('switch_port', models.CharField(blank=True, max_length=225, null=True)),
                ('notes', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=225, null=True)),
                ('product_number', models.CharField(blank=True, max_length=225, null=True)),
                ('asset_number', models.CharField(blank=True, max_length=225, null=True)),
                ('tm500_info_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm500_info_id_for', to='rpcTrack.TM500_INFO')),
            ],
        ),
        migrations.CreateModel(
            name='UE_LIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ue', models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='bts_pc',
            name='tm500_pc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_tm', to='rpcTrack.TM500_PC'),
        ),
        migrations.AddField(
            model_name='bts_pc',
            name='tt_info_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tt_info_id_for', to='rpcTrack.BTS_INFO'),
        ),
        migrations.AddField(
            model_name='bts_pc',
            name='tt_mod1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tt_mod_1', to='rpcTrack.BTS_MODULES'),
        ),
        migrations.AddField(
            model_name='bts_pc',
            name='tt_mod2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tt_mod_2', to='rpcTrack.BTS_MODULES'),
        ),
        migrations.AddField(
            model_name='bts_pc',
            name='tt_mod3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tt_mod_3', to='rpcTrack.BTS_MODULES'),
        ),
    ]
