# Generated by Django 2.1.3 on 2019-06-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='btsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bts', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='btsPC',
            fields=[
                ('displayName', models.CharField(max_length=100)),
                ('serverName', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('bts', models.CharField(max_length=50)),
                ('ue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='remotePC',
            fields=[
                ('serverName', models.GenericIPAddressField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tm500',
            fields=[
                ('serverName', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('tm_tenv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tm500PC',
            fields=[
                ('displayName', models.CharField(max_length=100)),
                ('serverName', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('bts', models.CharField(max_length=50)),
                ('ue', models.CharField(max_length=50)),
                ('tenv', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ueList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ue', models.CharField(max_length=50)),
            ],
        ),
    ]
