# Generated by Django 2.1.3 on 2019-06-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='btsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bts', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='btsPC',
            fields=[
                ('displayName', models.CharField(max_length=225)),
                ('serverName', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('domain', models.CharField(max_length=225)),
                ('bts', models.CharField(max_length=225)),
                ('ue', models.CharField(max_length=225)),
                ('fetch', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='remotePC',
            fields=[
                ('serverName', models.GenericIPAddressField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tm500',
            fields=[
                ('serverName', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('tm_tenv', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='tm500PC',
            fields=[
                ('displayName', models.CharField(max_length=225)),
                ('serverName', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('domain', models.CharField(blank=True, max_length=225)),
                ('bts', models.CharField(blank=True, max_length=225)),
                ('ue', models.CharField(max_length=225)),
                ('tenv', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ueList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ue', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='btsPCInfo',
            fields=[
                ('serverName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bts_info', serialize=False, to='rpcTrack.btsPC')),
                ('last_fetch', models.DateTimeField(auto_now=True)),
                ('WCDMAPilot', models.CharField(max_length=225)),
                ('DSPExplorer', models.CharField(max_length=225)),
                ('GTAPluginGiant', models.CharField(max_length=225)),
            ],
        ),
    ]
