# Generated by Django 2.1.3 on 2019-06-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpcTrack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btspcinfo',
            name='DSPExplorer',
        ),
    ]
