# Generated by Django 2.1.3 on 2019-06-04 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpcTrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='remotepc',
            name='displayName',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='logincredentials',
            name='serverName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpcTrack.remotePC'),
        ),
    ]
