# Generated by Django 2.1.3 on 2019-07-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpcTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bts_modules',
            name='assign',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1')], default='0', max_length=1, null=True),
        ),
    ]
