# Generated by Django 2.1.3 on 2019-06-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpcTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tm500pc',
            name='bts',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tm500pc',
            name='domain',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
