# Generated by Django 2.1.3 on 2019-06-04 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpcTrack', '0002_auto_20190604_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='hardwareDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bts', models.CharField(choices=[('FSMR2', 'FSMR2'), ('FSMR3', 'FSMR3'), ('FSMR4', 'FSMR4')], max_length=5)),
                ('serverName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpcTrack.remotePC')),
            ],
        ),
    ]
