# Generated by Django 2.1.3 on 2019-07-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpcTrack', '0002_auto_20190703_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bts_info',
            name='i_d',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
