# Generated by Django 2.1.3 on 2019-06-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpcTrack', '0002_remove_btspcinfo_dspexplorer'),
    ]

    operations = [
        migrations.AddField(
            model_name='btspcinfo',
            name='DSPExplorer',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='btspcinfo',
            name='GTAPluginGiant',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='btspcinfo',
            name='WCDMAPilot',
            field=models.CharField(default='', max_length=225),
        ),
    ]
