# Generated by Django 2.1.3 on 2019-06-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpcTrack', '0003_hardwaredetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaredetails',
            name='ue',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hardwaredetails',
            name='bts',
            field=models.CharField(max_length=50),
        ),
    ]
