# Generated by Django 2.1.3 on 2019-07-04 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpcTrack', '0003_auto_20190703_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TM500_INFO',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('rack', models.CharField(blank=True, max_length=225, null=True)),
                ('switch_port', models.CharField(blank=True, max_length=225, null=True)),
                ('notes', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=225, null=True)),
                ('product_number', models.CharField(blank=True, max_length=225, null=True)),
                ('asset_number', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TM500_PC',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=225)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('domain', models.CharField(blank=True, max_length=225, null=True)),
                ('rack', models.CharField(blank=True, max_length=225, null=True)),
                ('switch_port', models.CharField(blank=True, max_length=225, null=True)),
                ('notes', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=225, null=True)),
                ('product_number', models.CharField(blank=True, max_length=225, null=True)),
                ('asset_number', models.CharField(blank=True, max_length=225, null=True)),
                ('tm500_info_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm500_info_id_for', to='rpcTrack.TM500_INFO')),
            ],
        ),
        migrations.RemoveField(
            model_name='tm500pcinfo',
            name='serverName',
        ),
        migrations.AlterField(
            model_name='bts_pc',
            name='tm500_pc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_tm', to='rpcTrack.TM500_PC'),
        ),
        migrations.DeleteModel(
            name='tm500PC',
        ),
        migrations.DeleteModel(
            name='tm500PCInfo',
        ),
    ]
