# Generated by Django 2.1.3 on 2019-06-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpcTrack', '0003_auto_20190618_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btspcinfo',
            name='DSPExplorer',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='btspcinfo',
            name='GTAPluginGiant',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='btspcinfo',
            name='WCDMAPilot',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
    ]
