# Generated by Django 2.1.3 on 2019-07-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpcTrack', '0003_auto_20190709_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='document',
            field=models.FileField(blank=True, upload_to='C:\\Users\\krlee\\Downloads\\UPSCTTracker\\media'),
        ),
    ]
