# Generated by Django 2.1.3 on 2019-07-08 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpcTrack', '0004_auto_20190704_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='bts_pc',
            name='bts_mod1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bts_mod_1', to='rpcTrack.BTS_MODULES'),
        ),
        migrations.AddField(
            model_name='bts_pc',
            name='bts_mod2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bts_mod_2', to='rpcTrack.BTS_MODULES'),
        ),
        migrations.AddField(
            model_name='bts_pc',
            name='bts_mod3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bts_mod_3', to='rpcTrack.BTS_MODULES'),
        ),
        migrations.AddField(
            model_name='bts_pc',
            name='tt_mod1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tt_mod_1', to='rpcTrack.BTS_MODULES'),
        ),
        migrations.AddField(
            model_name='bts_pc',
            name='tt_mod2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tt_mod_2', to='rpcTrack.BTS_MODULES'),
        ),
        migrations.AddField(
            model_name='bts_pc',
            name='tt_mod3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tt_mod_3', to='rpcTrack.BTS_MODULES'),
        ),
    ]
