# Generated by Django 2.1.3 on 2019-06-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpcTrack', '0004_auto_20190604_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwaredetails',
            name='serverName',
        ),
        migrations.RemoveField(
            model_name='logincredentials',
            name='serverName',
        ),
        migrations.AddField(
            model_name='remotepc',
            name='bts',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotepc',
            name='domain',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotepc',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotepc',
            name='ue',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotepc',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='hardwareDetails',
        ),
        migrations.DeleteModel(
            name='loginCredentials',
        ),
    ]
